[workspace]
authors = ["John <JohnChangSu@gmail.com>"]
channels = ["conda-forge"]
name = "mojo_lbm"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build-src = "python buildLBM.py"
compiletest = "python compiletest.py"

[feature.dev.dependencies]
nodejs = "*" # Node, npm, and npx live here

[environments]
default = []
dev = ["dev"] # Developers activate or target this environment